# Generated by Django 5.1.4 on 2024-12-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='title',
        ),
    ]
